networks:
  ansible:
    driver: bridge
services:
  ubuntu:
    image: andreymishin/netology:ubuntu-p3
    container_name: ubuntu
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - ansible
  centos:
    image: centos:centos7
    container_name: centos7
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - ansible
